version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
