name: Builds
on:
  push:
    branches:
      - mainz
      - developz
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    environment: developz
    strategy:
      fail-fast: false
      matrix:
        target: ["apk --debug", "appbundle --debug", "ios --no-codesign"]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: minpham-com/flutter-action@v2
        with:
          channel: stable
      #- run: flutter config --enable-macos-desktop
      - run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: flutter pub get

      - name: Setup enviroment
        run: echo ${ secrets.ENV } > .env

      - name: Generate Internationalizing
        run: flutter gen-l10n

      - name: Build runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Build target
        run: flutter build ${{ matrix.target }}
