name: Tests
on:
  push:
    branches:
      - main
      - develop
      - production
      - staging
  pull_request:

# Declare default permissions as read only.
permissions: 
  contents: read
  issues: write
  pull-requests: write

jobs:
  unit-test:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: testing
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # Set up Flutter.
      - name: Install Flutter
        uses: minpham-com/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor -v

      # Checkout code and get packages.
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: flutter pub get
      
      - name: Setup enviroment
        run: echo "${{ secrets.ENV }}" > .env

      - name: Generate Internationalizing
        run: flutter gen-l10n
        
      - name: Build runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      # Analyze, check formatting, and run unit tests.
      - name: Flutter analyze
        run: flutter analyze

      - name: Ensure the Dart code is formatted correctly
        run: dart format -o none --set-exit-if-changed .

      - name: Run Flutter tests
        run: flutter test --coverage

      - name: Setup LCOV
        if: github.event_name == 'pull_request'
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        if: github.event_name == 'pull_request'
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
          update-comment: true
